// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk05dyVyjzk7pCMXo-F7lNMMiWvipyDNU',
    appId: '1:1014099622822:web:ca30150118e61be77eed67',
    messagingSenderId: '1014099622822',
    projectId: 'crm-touchwood',
    authDomain: 'crm-touchwood.firebaseapp.com',
    storageBucket: 'crm-touchwood.firebasestorage.app',
    measurementId: 'G-Y7C16TGXWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEU5mMq5dSONmQRxvoFLoazTwLC-rKKac',
    appId: '1:1014099622822:android:bc2a69e0265adfbd7eed67',
    messagingSenderId: '1014099622822',
    projectId: 'crm-touchwood',
    storageBucket: 'crm-touchwood.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeeU3q7xohTPR3qZxS-AOpzqVL__5RP74',
    appId: '1:1014099622822:ios:93c908af21f4073e7eed67',
    messagingSenderId: '1014099622822',
    projectId: 'crm-touchwood',
    storageBucket: 'crm-touchwood.firebasestorage.app',
    iosBundleId: 'com.app.teamcrm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeeU3q7xohTPR3qZxS-AOpzqVL__5RP74',
    appId: '1:1014099622822:ios:93c908af21f4073e7eed67',
    messagingSenderId: '1014099622822',
    projectId: 'crm-touchwood',
    storageBucket: 'crm-touchwood.firebasestorage.app',
    iosBundleId: 'com.app.teamcrm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCk05dyVyjzk7pCMXo-F7lNMMiWvipyDNU',
    appId: '1:1014099622822:web:bc510c43150693f17eed67',
    messagingSenderId: '1014099622822',
    projectId: 'crm-touchwood',
    authDomain: 'crm-touchwood.firebaseapp.com',
    storageBucket: 'crm-touchwood.firebasestorage.app',
    measurementId: 'G-750T8STEPS',
  );
}
